version: '3'

services:
  database:
    image: postgres
    container_name: pg_container
    volumes:
       - /$HOME/docker/volumes/postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_container
    links:
     - "database"
    environment:
      - PGPASSWORD=newpassword
      - PGUSER=postgres
      - PGHOST=database
      - PGPORT=5432
    depends_on:
      - database

volumes:
  pgdata: {}